[build]
  base = "."
  command = "npm install && CI= npm run build"
  publish = "build"
  functions = "functions" 

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
