[build]
  command = "npm install && CI=false NODE_ENV=production npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
