[build]
    base = "Frontend"
    command = "CI= npm run build && npm run build"
    publish = "Frontend/build"
    function = "functions"

[[redirects]] 
    from = "/*"
    to = "/index.html"
    status = 200
