[build]
  base = "Frontend"
  command = "CI= npm run build"
  publish = "Frontend/build"
  functions = "Frontend/functions" 

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
