[build]
  base = "Frontend"
  command = "npm install && npm run build"
  publish = "Frontend/build"
  functions = "Frontend/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
