[build]
  base = "Frontend"
  command = "cd Frontend && npm install --legacy-peer-deps && npm uninstall husky --save-dev && npm run build"
  publish = "Frontend/build"
  functions = "Frontend/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
