web: gunicorn --workers 3 --bind 0.0.0.0:$PORT --timeout 120 --log-level=debug --access-logfile - --error-logfile - porfolio.wsgi:application
release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
